# Generated by Django 3.1.7 on 2021-06-01 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import summa.manager
import summa.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=55, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=155, verbose_name='Sobrenome')),
                ('matricula', models.CharField(max_length=55, unique=True)),
                ('email', models.EmailField(max_length=155, unique=True, verbose_name='Email')),
                ('foto', models.FileField(blank=True, null=True, upload_to=summa.models.get_file_path, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
            },
            managers=[
                ('objects', summa.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=9, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=55, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=55, verbose_name='Cidade')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaAtividadeComplementar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('macroatividades', models.CharField(max_length=55, verbose_name='Macroatividades')),
                ('carga_horaria_maxima_categoria', models.IntegerField(verbose_name='Carga Horária Máxima da Categoria para este Curso')),
                ('descricao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria Atividade Complementar',
                'verbose_name_plural': 'Categorias Atividades Complementares',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=155, null=True, verbose_name='Nome Fantasia')),
                ('telefone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uf', models.CharField(max_length=2, unique=True, verbose_name='UF')),
                ('estado', models.CharField(max_length=55, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nome', models.CharField(max_length=55, verbose_name='Nome')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='summa.campus')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('categoria_atividade_complementar', models.ManyToManyField(to='summa.CategoriaAtividadeComplementar')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='summa.curso')),
            ],
            options={
                'verbose_name': 'Categoria Curso',
                'verbose_name_plural': 'Categorias Cursos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='summa.estado'),
        ),
        migrations.AddField(
            model_name='campus',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campus', to='summa.instituicao'),
        ),
        migrations.CreateModel(
            name='AtividadeComplementar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('carga_horaria_informada', models.IntegerField(verbose_name='Carga Horária Informada')),
                ('carga_horaria_integralizada', models.IntegerField(blank=True, null=True, verbose_name='Carga Horária Integralizada')),
                ('justificativa', models.TextField(blank=True, max_length=500, null=True, verbose_name='justificativa')),
                ('certificado_img', models.FileField(upload_to=summa.models.get_file_path, verbose_name='Certificado')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='summa.categoriaatividadecomplementar')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='summa.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade Complementar',
                'verbose_name_plural': 'Atividades Complementares',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='summa.curso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
