# Generated by Django 3.1.7 on 2021-06-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriacurso',
            name='categoria_atividade_complementar',
        ),
        migrations.AddField(
            model_name='categoriacurso',
            name='categoria_atividade_complementar',
            field=models.ManyToManyField(to='summa.CategoriaAtividadeComplementar'),
        ),
    ]
