# Generated by Django 3.1.7 on 2021-11-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='status',
            field=models.CharField(choices=[('em_validação', 'em validação'), ('aprovado', 'aprovado'), ('recusado', 'recusado')], default='em_validação', max_length=20, verbose_name='Status'),
        ),
    ]
