# Generated by Django 3.1.7 on 2021-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecomplementar',
            name='status',
            field=models.CharField(choices=[('em validação', 'em validação'), ('aprovado', 'aprovado'), ('recusado', 'recusado')], default='em validação', max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
