# Generated by Django 3.1.7 on 2021-06-01 01:37

from django.db import migrations
import summa.manager


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aluno',
            managers=[
                ('objects', summa.manager.UserManager()),
            ],
        ),
    ]
