# Generated by Django 3.1.7 on 2021-11-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0002_auto_20211124_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='status',
            field=models.CharField(choices=[('em validação', 'em_validação'), ('aprovado', 'aprovado'), ('recusado', 'recusado')], default='em validação', max_length=20, verbose_name='Status'),
        ),
    ]
