# Generated by Django 3.1.7 on 2021-06-06 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0003_auto_20210605_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='summa.categoriacurso'),
        ),
    ]
