# Generated by Django 3.1.7 on 2021-06-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0003_auto_20210601_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaatividadecomplementar',
            name='carga_horaria_maxima_categoria',
        ),
        migrations.AddField(
            model_name='curso',
            name='qtd_horas_conclusao',
            field=models.IntegerField(default=120, verbose_name='Quantidade de horas para obtenção do diploma'),
            preserve_default=False,
        ),
    ]
