# Generated by Django 3.1.7 on 2021-06-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0004_auto_20210601_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='qtd_horas_conclusao',
            field=models.IntegerField(verbose_name='Quantidade mínima de horas para obtenção do diploma'),
        ),
    ]
