# Generated by Django 3.1.7 on 2021-06-06 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0005_auto_20210605_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriacurso',
            name='categoria_atividade_complementar',
        ),
        migrations.AddField(
            model_name='categoriacurso',
            name='categoria_atividade_complementar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='summa.categoriaatividadecomplementar'),
            preserve_default=False,
        ),
    ]
