# Generated by Django 3.1.7 on 2021-06-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0009_auto_20210602_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='CNPJ'),
        ),
    ]
