# Generated by Django 3.1.7 on 2021-06-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0010_auto_20210606_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacurso',
            name='categoria_atividade_complementar',
            field=models.ManyToManyField(to='summa.CategoriaAtividadeComplementar'),
        ),
    ]
