# Generated by Django 3.1.7 on 2021-06-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0010_auto_20210602_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecomplementar',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
