# Generated by Django 3.1.7 on 2021-06-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0011_atividadecomplementar_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='CNPJ'),
        ),
    ]
