# Generated by Django 3.1.7 on 2021-06-06 06:56

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0011_categoriacurso_categoria_atividade_complementar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='categoria',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='usuario', chained_model_field='curso', on_delete=django.db.models.deletion.CASCADE, sort=False, to='summa.categoriacurso'),
        ),
    ]
