# Generated by Django 3.1.7 on 2021-06-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0012_auto_20210606_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='summa.categoriacurso'),
        ),
    ]
