# Generated by Django 3.1.7 on 2021-06-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0012_auto_20210602_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='telefone',
            field=models.CharField(default='(24) 2471-9004', max_length=16, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
