# Generated by Django 3.1.7 on 2021-06-02 22:45

from django.db import migrations, models
import summa.models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0014_campus_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='modelo_certificado',
            field=models.FileField(default='trocar', upload_to=summa.models.get_file_path, verbose_name='Imagem de fundo certificado'),
            preserve_default=False,
        ),
    ]
