# Generated by Django 3.1.7 on 2021-06-06 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0014_auto_20210606_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCursoAtividadeComplementar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('categoria_atividade_complementar', models.ManyToManyField(to='summa.CategoriaCurso')),
            ],
            options={
                'verbose_name': 'Categoria Curso Atividade Complementar',
                'verbose_name_plural': 'Categoria Curso Atividades complementares',
                'ordering': ['id'],
            },
        ),
    ]
