# Generated by Django 3.1.7 on 2021-06-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0015_categoriacursoatividadecomplementar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaCursoAtividadeComplementar',
        ),
    ]
