# Generated by Django 3.1.7 on 2021-06-03 18:10

from django.db import migrations, models
import summa.models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0015_campus_modelo_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='modelo_certificado',
            field=models.FileField(upload_to=summa.models.get_file_path, verbose_name='Imagem de fundo certificado (1080x755 px)'),
        ),
    ]
