# Generated by Django 3.1.7 on 2021-06-06 21:57

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0018_auto_20210606_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecomplementar',
            name='cnpj',
            field=models.CharField(default='Prefeitura de Vassouras', max_length=18, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='categoria',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='curso', chained_model_field='curso', on_delete=django.db.models.deletion.CASCADE, sort=False, to='summa.categoriaatividadecomplementar'),
        ),
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='empresa',
            field=models.CharField(max_length=155, verbose_name='Empresa/Instituição'),
        ),
    ]
