# Generated by Django 3.1.7 on 2021-06-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0019_auto_20210606_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
    ]
