# Generated by Django 3.1.7 on 2021-06-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0020_auto_20210606_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='email',
            field=models.EmailField(blank=True, max_length=155, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='campus',
            name='site',
            field=models.URLField(default='https://universidadedevassouras.edu.br', max_length=155, verbose_name='Site'),
            preserve_default=False,
        ),
    ]
