# Generated by Django 3.1.7 on 2021-06-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0021_auto_20210606_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadecomplementar',
            name='empresa',
            field=models.CharField(max_length=255, verbose_name='Empresa/Instituição'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='email',
            field=models.EmailField(default='suporte@universidadedevassouras.edu.br', max_length=155, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
