# Generated by Django 3.1.7 on 2021-06-07 23:15

from django.db import migrations, models
import summa.models


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0022_auto_20210607_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=summa.models.get_file_path, verbose_name='Foto'),
        ),
    ]
