# Generated by Django 3.1.7 on 2021-06-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summa', '0023_auto_20210607_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
